spring:
  application:
    name: livraison-v2
  config:
    import: optional:file:.env.properties
  profiles:
    active: ${ACTIVE_PROFILE}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true
  ai:

    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama2
        optimizer:
          type: plus_proche_voisin

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql



