spring:
  application:
    name: livraison-v2
  config:
    import: optional:file:.env.properties
  profiles:
    active: ${ACTIVE_PROFILE}

  # Spring AI properties – elles fonctionnent à l'exécution
  ai:
    provider: ollama
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama2:latest

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

optimizer:
  type: ai_optimizer

server:
  port: ${SERVER_PORT}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.ai: DEBUG
    com.livraison.optimizer: DEBUG
    org.springframework.web: DEBUG
