# ============================================
# ðŸ§© Profil DEV - Base H2 + Liquibase
# ============================================

spring:
  datasource:
    url: jdbc:h2:mem:livraison;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none   # IMPORTANT: Liquibase gÃ¨re le schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false   # IMPORTANT pour Ã©viter le circular dependency

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    # facultatif selon besoin:
    # contexts: dev
    # default-schema: PUBLIC
    # drop-first: false
sql:
  init:
    mode: never
server:
  port: 8082
